(function(g){var window=this;'use strict';var YW=function(W){W.isActive()||W.start()},nR=function(W){const z={languageCode:W.languageCode,
languageName:W.languageName,displayName:g.Y2(W),kind:W.kind,name:W.name,id:W.id,is_servable:W.S,is_default:W.isDefault,is_translateable:W.isTranslateable,vss_id:W.vssId};W.xtags&&(z.xtags=W.xtags);W.captionId&&(z.captionId=W.captionId);W.translationLanguage&&(z.translationLanguage=W.translationLanguage);return z},uQf=function(W,z){const P=new g.VV;
P.languageCode=W.languageCode;P.languageName=W.languageName;P.name=W.name;P.displayName=W.displayName;P.kind=W.kind;P.isDefault=!1;P.S=W.S;P.isTranslateable=W.isTranslateable;P.vssId=W.vssId;P.url=W.url;P.translationLanguage=z;W.xtags&&(P.xtags=W.xtags);W.captionId&&(P.captionId=W.captionId);return P},ZH=function(W,z){return z?W.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},GL2=function(W){return g.C_(W)||W.Y("web_enable_caption_language_preference_stickiness")},NUF=async function(W,z){W=
W+"|"+z;
z=await g.Zu();if(!z)throw g.HY("gct");return(await g.qC(z)).get("captions",W)},fJF=function(W,z,P){NUF(W,z).then(B=>{B&&P(B.trackData,new g.VV(B.metadata))})},ju=function(W){if(!W_y.test(W))throw Error("'"+W+"' is not a valid hex color");
W.length==4&&(W=W.replace(zPF,"#$1$1$2$2$3$3"));W=W.toLowerCase();W=parseInt(W.slice(1),16);return[W>>16,W>>8&255,W&255]},Pxn=function(){var W={};
let z="suggest_correction"in g.Rh?g.Rh.suggest_correction:"Edit caption";z=z||"";for(let P in W){const B=()=>String(W[P]);
z=z.replace(new RegExp("\\$\\{"+P+"\\}","gi"),B);z=z.replace(new RegExp("\\$"+P,"gi"),B)}return z},F7=function(){return g.PY("yt-player-caption-display-settings")},B6f=function(W,z){g.Jv(z,P=>W.equals(P))||z.push(W)},$W=function(W,z){switch(z.kind){case "asr":B6f(z,W.N);
break;default:B6f(z,W.B)}},cRU=async function(W,z,P){W.B=g.pj(z,P)},MXn=function(W,z){let P=g.Bv(W.segments,z);
P>=0||P<0&&(-P-1)%2===1||(P=-P-1,P>0&&z-W.segments[P-1]===1&&P<W.segments.length&&W.segments[P]-z===1?(g.Ts(W.segments,P),g.Ts(W.segments,P-1)):P>0&&z-W.segments[P-1]===1?W.segments[P-1]=z:P<W.segments.length&&W.segments[P]-z===1?W.segments[P]=z:(g.Wv(W.segments,P,0,z),g.Wv(W.segments,P+1,0,z)))},tXF=function(W){return W.S&&W.S.L?W.S.L+W.player.e3()<W.player.getCurrentTime():!1},q2y=function(W,z){if(W.policy.Rw&&W.player.QS()){var P=g.eP(z,W.policy,{});
P.set("pot",W.player.QS());P=P.nI()}else P=g.eP(z,W.policy,{}).nI();const B={format:"RAW",withCredentials:!0};if(W.policy.e4){B.method="POST";const t=z.L;t&&Object.keys(t).length>0?B.postBody=g.dA(t,g.bi):B.postBody=(0,g.rv)([120,0])}W.G&&(B.responseType="arraybuffer");let c=++W.S4;const M=(0,g.C)();W.B=g.Jd(P,B,3,100,-1,t=>{t.errorCode==="net.timeout"&&W.player.j("capnt",{rn:c++})}).then(t=>{if(W.policy.oS&&c%100===1){var q=(0,g.C)();
W.player.j("caprsp",{rn:c,ms:q-M,kb:(t.xhr.responseText.length/1024).toFixed()})}a:{t=t.xhr;W.hp();if(W.N){var w=!(W.G?t.response:t.responseText)||t.status>=400;if(q=g.qH(t)){t=g.eP(W.N,W.policy,{});W.N.Ih(t,q);q2y(W,W.N);break a}w?W.player.j("capfail",{status:t.status}):(g.at("fcb_r",(0,g.C)(),W.player.getVideoData()?.O||""),q=W.N.b9[0],w=q.PF,W.J!=null&&W.K!==w&&(W.G?W.J(t.response,(q.startTime+W.player.e3())*1E3):W.J(t.responseText,(q.startTime+W.player.e3())*1E3),W.K=w))}W.N=null;W.B=null}}).DH(t=>
{W.N=null;
W.B=null;W.player.j("capfail",{rn:c,status:t.xhr?.status})});
W.N=z;MXn(W.L,W.N.b9[0].PF)},wXe=function(W,z){return z!=null&&z in W.B.S?W.B.S[z]:null},o5Y=function(W,z,P){const B=[];
for(const c in W.B.S){if(!W.B.S.hasOwnProperty(c))continue;const M=W.B.S[c];if(g.tp(M,P||null)){const t=M.info.captionTrack;t&&t.languageCode===z&&B.push(M)}}return B.length?B[0]:null},kcf=function(W,z){const P=[];
for(const c in W.B.S){if(!W.B.S.hasOwnProperty(c))continue;var B=W.B.S[c];if(g.tp(B,z||null)){let M=B.info.id,t=M,q=`.${M}`,w="",y="";if(B=B.info.captionTrack)M=B.languageCode,t=B.displayName,q=B.vssId,w=B.kind,y=B.id;else{{B=M;let L=g.cOY.get(B);L==null&&(L=yRD[B]||yRD[B.replace(/-/g,"_")],g.cOY.set(B,L));B=L}t=B||t}P.push(new g.VV({id:c,languageCode:M,languageName:t,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:q,kind:w,captionId:y}))}}return P},Ru=function(W){if(typeof DOMParser!="undefined")return g.g0(new DOMParser,
g.ua(W),"application/xml");
throw Error("Your browser does not support loading xml documents");},L_v=function(W,z,P,B){let c=z/360*16;
z>=W&&(W=640,B>P*1.3&&(W=480),c=P/W*16);return c},g5f=function(W){let z=1+.25*(W.fontSizeIncrement||0);
if(W.offset===0||W.offset===2)z*=.8;return z},d6o=function(W,z){let P="vertical-rl";
W.S.jb===1&&(P="vertical-lr");g.B_&&(P=P==="vertical-lr"?"tb-lr":"tb-rl");g.vs(z,"-o-writing-mode",P);g.vs(z,"-webkit-writing-mode",P);g.vs(z,"writing-mode",P);g.vs(z,"text-orientation","upright");g.dW(z,"ytp-vertical-caption");W.N.params.E7===3&&(g.vs(z,"text-orientation",""),g.vs(z,"transform","rotate(180deg)"))},XXf=function(W,z){const P={};
var B=z.background?z.background:W.S.oO.background;if(z.backgroundOpacity!=null||z.background){var c=z.backgroundOpacity!=null?z.backgroundOpacity:W.S.oO.backgroundOpacity;B=ju(B);P.background="rgba("+B[0]+","+B[1]+","+B[2]+","+c+")";W.fK&&(P["box-decoration-break"]="clone",P["border-radius"]=`${W.j4*.375}px`)}if(z.fontSizeIncrement!=null||z.offset!=null)P["font-size"]=`${W.qs*g5f(z)}px`;B=1;c=z.color||W.S.oO.color;if(z.color||z.textOpacity!=null)c=ju(c),B=z.textOpacity==null?W.S.oO.textOpacity:z.textOpacity,
c="rgba("+c[0]+","+c[1]+","+c[2]+","+B+")",P.color=c,P.fill=c;var M=z.charEdgeStyle;M===0&&(M=void 0);if(M){c=`rgba(34, 34, 34, ${B})`;let w=`rgba(204, 204, 204, ${B})`;z.Kx&&(w=c=z.Kx);const y=W.qs/16/2,L=Math.max(y,1);var t=Math.max(2*y,1),q=Math.max(3*y,1);const k=Math.max(5*y,1);B=[];switch(M){case 4:for(;q<=k;q+=y)B.push(`${t}px ${t}px ${q}px ${c}`);break;case 1:t=window.devicePixelRatio>=2?.5:1;for(M=L;M<=q;M+=t)B.push(`${M}px ${M}px ${c}`);break;case 2:B.push(`${L}px ${L}px ${w}`);B.push(`-${L}px -${L}px ${c}`);
break;case 3:for(q=0;q<5;q++)B.push(`0 0 ${t}px ${c}`)}P["text-shadow"]=B.join(", ")}c="";switch(z.fontFamily){case 1:c='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:c='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:c='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:c='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:c='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:c=g.w9()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:c='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}c&&(P["font-family"]=c);c=z.offset;c==null&&(c=W.S.oO.offset);switch(c){case 0:P["vertical-align"]="sub";break;case 2:P["vertical-align"]="super"}z.fontFamily===7&&(P["font-variant"]="small-caps");z.bold&&(P["font-weight"]="bold");z.italic&&(P["font-style"]="italic");z.underline&&
(P["text-decoration"]="underline");z.Dv&&(P.visibility="hidden");z.A1===1&&W.G&&(P["text-combine-upright"]="all",P["text-orientation"]="mixed",c=g.kX||g.bU,W.N.params.E7===3?P.transform=c?"rotate(90deg)":"rotate(180deg)":c&&(P.transform="rotate(-90deg)"));if(z.textEmphasis===1||z.textEmphasis===2||z.textEmphasis===3||z.textEmphasis===4||z.textEmphasis===5)if(g.kX)P["font-weight"]="bold";else switch(P["text-emphasis-style"]="filled circle",P["text-emphasis-color"]="currentcolor",P["webkit-text-emphasis"]=
"filled circle",z.textEmphasis){case 4:case 3:P["text-emphasis-position"]="under left";P["webkit-text-emphasis-position"]="under left";break;case 5:case 2:P["text-emphasis-position"]="over right",P["webkit-text-emphasis-position"]="over right"}return P},xW=function(W){W=W.split("px");
return W.length>0?(W=Number(W[0]))?W:0:0},lq2=function(W,z,P){W.YA=W.YA||!!P;
const B={};Object.assign(B,W.S.oO);Object.assign(B,P||z.S);Object.assign(B,W.tT.oO);(P=!W.O)&&i1k(W);let c=W.R0&&W.m7&&g.VO(B,W.m7)?W.R0:S2U(W,B);const M=typeof z.text==="string",t=M?z.text.split("\n"):[z.text];for(let w=0;w<t.length;w++){var q=w>0||!z.append;const y=t[w];q&&!P?(i1k(W),c=S2U(W,B)):q&&P&&(P=!1);y&&(c.appendChild(M?g.X6(y):y),M||y.tagName!=="RUBY"||y.childElementCount!==4||g.kX||!g.pl(y.children[2],"text-emphasis")||(q=W.G?"padding-right":"padding-top",g.pl(y.children[2],"text-emphasis-position")&&
(q=W.G?"padding-left":"padding-bottom"),g.wK?g.vs(c,q,"1em"):g.vs(c,q,"0.5em")))}W.m7=B;W.R0=c;W.J.push(z)},i1k=function(W){W.O=g.dK("SPAN");
g.vs(W.O,{display:"block"});g.dW(W.O,"caption-visual-line");W.K.appendChild(W.O)},S2U=function(W,z){const P=g.dK("SPAN");
g.vs(P,{display:"inline-block","white-space":"pre-wrap"});g.vs(P,XXf(W,z));P.classList.add("ytp-caption-segment");W.O.appendChild(P);P.previousElementSibling&&(g.vs(P.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.vs(P,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return P},m6Y=function(W,z,P){if(W===255&&z===255||!W&&!z)return{Xq:W,
Zy:z,result:0};W=K_7[W];z=K_7[z];if(W&128){var B;if(B=!(z&128))B=z,B=P.Lm()&&P.Zy===B;if(B)return{Xq:W,Zy:z,result:1}}else if(z&128&&1<=W&&W<=31)return{Xq:W,Zy:z,result:2};return{Xq:W,Zy:z,result:3}},O1k=function(W,z,P,B){z===255&&P===255||!z&&!P?(++W.N===45&&W.reset(),W.L.B.clear(),W.G.B.clear()):(W.N=0,D6O(W.L,z,P,B))},Y2n=function(W,z){W.S.sort((P,B)=>{const c=P.time-B.time;
return c===0?P.order-B.order:c});
for(const P of W.S)W.time=P.time,P.type===0?O1k(W,P.gT,P.BV,z):P.type===1&&W.B&496&&D6O(W.G,P.gT,P.BV,z);W.S.length=0},$6f=function(W,z){switch(W){case 0:return n5H[(z&127)-32];
case 1:return Z1H[z&15];case 2:return j87[z&31];case 3:return F_F[z&31]}return 0},vE=function(W,z){if(W.style.type===3){var P=0,B=0,c=W.G.time+0,M="",t="",q=c;
for(var w=1;w<=15;++w){var y=!1;for(var L=B?B:1;L<=32;++L){var k=W.N[w][L];if(k.S!==0){P===0&&(P=w,B=L);y=String.fromCharCode(k.S);var d=k.timestamp;d<c&&(c=d);k.timestamp=q;t&&(M+=t,t="");M+=y;y=!0}if((k.S===0||L===32)&&y){t="\n";break}else if(B&&!y)break}if(P&&!y)break}M&&z.L(P,B,c,q,M)}else for(B=P=0,M=c=W.G.time+0,t=1;t<=15;++t)for(q="",w=1;w<=32;++w)if(L=W.N[t][w],k=L.S,k!==0&&(P===0&&(P=t,B=w),y=String.fromCharCode(k),d=L.timestamp,d<=c&&(c=d),q+=y,L.reset()),w===32||k===0)q&&z.L(P,B,c,M,q),
c=M,q="",B=P=0},sO=function(W){return W.N[W.row][W.B]},rZ=function(W,z,P){z>=2&&W.B>1&&(--W.B,sO(W).S=0);
const B=sO(W);B.timestamp=W.G.time+0;B.S=$6f(z,P);W.B<32&&W.B++},RPk=function(W,z,P,B){for(let t=0;t<B;t++)for(let q=0;q<=32;q++){var c=W.N[z+t][q],M=W.N[P+t][q];
c.S=M.S;c.timestamp=M.timestamp}},Iu=function(W,z,P){for(let B=0;B<P;B++)for(let c=0;c<=32;c++)W.N[z+B][c].reset()},pR=function(W){W.row=W.S>0?W.S:1;
W.B=1;Iu(W,0,15)},x6Y=function(W){W.style.set(1);
W.S=W.L;W.S.S=0;W.S.style=W.style;W.N.mode=1<<W.S.L},h9=function(W,z,P){const B=W.B;
let c=!1;switch(W.style.get()){case 4:case 1:case 2:W.style.get()===4&&B.S>0||(vE(B,P),pR(W.B),pR(W.L),B.row=15,B.S=z,c=!0)}W.style.set(3);W.S=B;W.S.style=W.style;W.N.mode=1<<B.L;c?B.B=1:B.S!==z&&(B.S>z?(vE(B,P),Iu(B,B.row-B.S,z)):B.row<z&&(z=B.S),B.S=z)},v5v=function(W){W.style.set(4);
W.S=W.text;W.S.style=W.style;W.N.mode=1<<W.S.L},D6O=function(W,z,P,B){W.B.update();
z=m6Y(z,P,W.B);switch(z.result){case 0:return;case 1:case 2:return}var c=z.Xq;z=z.Zy;if(32<=c||!c)W.S.mode&W.S.B&&(P=c,P&128&&(P=127),z&128&&(z=127),W=W.L.S,P&96&&rZ(W,0,P),z&96&&rZ(W,0,z),P!==0&&z!==0&&W.style.type===3&&vE(W,B));else if(c&16)a:if(!W.B.matches(c,z)&&(P=W.B,P.Xq=c,P.Zy=z,P.state=2,P=c&8?W.K:W.N,W.L=P,W.S.mode=1<<(W.G<<2)+(P.G<<1)+(P.style.type===4?1:0),(W.S.mode|1<<(W.G<<2)+(P.G<<1)+(P.style.type!==4?1:0))&W.S.B))if(z&64){B=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(c&7)<<1|z>>5&1];
W=z&16?((z&14)>>1)*4:0;z=P.S;switch(P.style.get()){case 4:B=z.row;break;case 3:if(B!==z.row){if(B<z.S&&(B=z.S,B===z.row))break;var M=1+z.row-z.S;const t=1+B-z.S;RPk(z,t,M,z.S);P=M;c=z.S;t<M?(M=t+c-M,M>0&&(P+=M,c-=M)):(M=M+c-t,M>0&&(c-=M));Iu(z,P,c)}}z.row=B;z.B=W+1}else switch(c&7){case 1:switch(z&112){case 32:rZ(P.S,0,32);break a;case 48:z===57?(B=P.S,sO(B).S=0,B.B<32&&B.B++):rZ(P.S,1,z&15)}break;case 2:z&32&&rZ(P.S,2,z&31);break;case 3:z&32&&rZ(P.S,3,z&31);break;case 4:case 5:if(32<=z&&z<=47)switch(z){case 32:x6Y(P);
break;case 33:B=P.S;B.B>1&&(--B.B,sO(B).S=0);break;case 36:B=P.S;W=sO(B);for(z=0;z<=15;z++)for(P=0;P<=32;P++)if(B.N[z][P]===W){for(;P<=32;P++)B.N[z][P].reset();break}break;case 37:h9(P,2,B);break;case 38:h9(P,3,B);break;case 39:h9(P,4,B);break;case 40:rZ(P.S,0,32);break;case 41:B=P;B.style.set(2);B.S=B.B;B.S.S=0;B.S.style=B.style;B.N.mode=1<<B.S.L;break;case 42:B=P;W=B.text;W.S=15;W.style.set(4);pR(W);v5v(B);break;case 43:v5v(P);break;case 44:W=P;z=W.B;switch(W.style.get()){case 1:case 2:case 3:vE(z,
B)}Iu(z,0,15);break;case 45:b:{z=P;W=z.S;switch(z.style.get()){default:case 2:case 1:break b;case 4:if(W.row<15){++W.row;W.B=1;break b}break;case 3:}W.S<2&&(W.S=2,W.row<W.S&&(W.row=W.S));z=W.row-W.S+1;vE(W,B);RPk(W,z,z+1,W.S-1);Iu(W,W.row,1)}break;case 46:Iu(P.L,0,15);break;case 47:W=P,vE(W.B,B),W.L.updateTime(W.N.time+0),B=W.L,W.L=W.B,W.B=B,x6Y(W)}break;case 7:switch(z){case 33:case 34:case 35:B=P.S,(B.B+=z&3)>32&&(B.B=32)}}},rRk=function(W,z,P,B,c,M,t){var q=M[0];
let w=t[q.getAttribute("p")];if(w.sy===1){var y=M[1],L=M[2];M=M[3];q.getAttribute("t");y.getAttribute("t");L.getAttribute("t");M.getAttribute("t");q.getAttribute("p");y.getAttribute("p");M.getAttribute("p");t=t[L.getAttribute("p")];q=s8o(q.textContent,y.textContent,L.textContent,M.textContent,t);return new eu(W,z,c,P,q,B,w)}switch(w.sy){case 9:case 10:w.textEmphasis=1;break;case 11:w.textEmphasis=2;break;case 12:w.textEmphasis=3;break;case 13:w.textEmphasis=4;break;case 14:w.textEmphasis=5}return new eu(W,
z,c,P,q.textContent||"",B,w)},s8o=function(W,z,P,B,c){var M=g.w9();
const t=M?g.dK("DIV"):g.dK("RUBY"),q=g.dK("SPAN");q.textContent=W;t.appendChild(q);W=M?g.dK("DIV"):g.dK("RP");W.textContent=z;t.appendChild(W);z=M?g.dK("DIV"):g.dK("RT");z.textContent=P;t.appendChild(z);P=c.sy;if(P===10||P===11||P===12||P===13||P===14)if(g.vs(z,"text-emphasis-style","filled circle"),g.vs(z,"text-emphasis-color","currentcolor"),g.vs(z,"webkit-text-emphasis","filled circle"),c.sy===11||c.sy===13)g.vs(z,"webkit-text-emphasis-position","under left"),g.vs(z,"text-emphasis-position","under left");
P=!0;if(c.sy===4||c.sy===7||c.sy===12||c.sy===14)g.vs(t,"ruby-position","over"),g.vs(t,"-webkit-ruby-position","before");else if(c.sy===5||c.sy===6||c.sy===11||c.sy===13)g.vs(t,"ruby-position","under"),g.vs(t,"-webkit-ruby-position","after"),P=!1;c=M?g.dK("DIV"):g.dK("RP");c.textContent=B;t.appendChild(c);M&&(B=P,g.vs(t,{display:"inline-block",position:"relative"}),M=t.firstElementChild.nextElementSibling,g.vs(M,"display","none"),M=M.nextElementSibling,g.vs(M,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.vs(t.lastElementChild,"display","none"),B?(g.vs(t,"padding-top","0.6em"),g.vs(M,"top","0")):(g.vs(t,"padding-bottom","0.6em"),g.vs(M,"bottom","0")));return t},IqH=function(W){const z="_"+bs++;
return new QC(0,0x8000000000000,0,z,W)},au=function(W,z){W=W.getAttribute(z);
if(W!=null)return Number(W)},HE=function(W,z){W=W.getAttribute(z);
if(W!=null)return W==="1"},UO=function(W,z){W=au(W,z);
return W!==void 0?W:null},EO=function(W,z){W=W.getAttribute(z);
if(W!=null)return J9.test(W),W},pXo=function(W,z){const P={},B=z.getAttribute("ws");
Object.assign(P,B?W.O[B]:W.L);W=UO(z,"mh");W!=null&&(P.d8=W);W=UO(z,"ju");W!=null&&(P.textAlign=W);W=UO(z,"pd");W!=null&&(P.E7=W);W=UO(z,"sd");W!=null&&(P.jb=W);W=EO(z,"wfc");W!=null&&(P.windowColor=W);z=au(z,"wfo");z!==void 0&&(P.windowOpacity=z/255);return P},hPH=function(W,z){const P={},B=z.getAttribute("wp");
B&&Object.assign(P,W.J[B]);W=UO(z,"ap");W!=null&&(P.xm=W);W=au(z,"cc");W!=null&&(P.Xv=W);W=au(z,"ah");W!=null&&(P.xj=W);W=au(z,"rc");W!=null&&(P.ow=W);z=au(z,"av");z!=null&&(P.yS=z);return P},ePv=function(W,z,P,B){let c={};
Object.assign(c,hPH(W,z));Object.assign(c,pXo(W,z));B?g.VO(c,W.L)?(B=W.G,c=W.L):B="_"+bs++:B=z.getAttribute("id")||"_"+bs++;W=au(z,"t")+P;z=au(z,"d")||0x8000000000000;if(c.E7===2||c.E7===3)P=c.ow,c.ow=c.Xv,c.Xv=P;return new QC(W,z,0,B,c)},VC=function(W){W=g.mh(Math.round(W),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-W.length)+W},b1U=function(W,z,P,B,c){B===0&&(B=0x8000000000000);
const M={};z.wpWinPosId&&Object.assign(M,W.L.get(z.wpWinPosId));z.wsWinStyleId&&Object.assign(M,W.G.get(z.wsWinStyleId));W=z.rcRowCount;W!==void 0&&(M.ow=W);z=z.ccColCount;z!==void 0&&(M.Xv=z);if(M.E7===2||M.E7===3)z=M.ow,M.ow=M.Xv,M.Xv=z;return new QC(P,B,0,c,M)},CR=function(W){const z=W.byteOffset;
W.byteOffset+=1;return W.S.getUint8(z)},TG=function(W){const z=W.byteOffset;
W.byteOffset+=4;return W.S.getUint32(z)},H1y=function(W){if(typeof W==="string")return!1;
W=new Q8O(W,0);return aq7(W)},aq7=function(W){if(!(W.byteOffset<W.S.byteLength)||TG(W)!==1380139777)return!1;
W.version=CR(W);if(W.version>1)return!1;CR(W);CR(W);CR(W);return!0},U6y=function(W,z){if(!z)return"";
W.G&&W.N.params.jb!==1&&(z*=-1);return`translate${W.G?"X":"Y"}(${z}px)`},JRD=function(W){W.Gj=Array.from(W.element.getElementsByClassName("caption-visual-line"));
for(var z=W.N.params.ow,P=0,B=0,c=W.Gj.length-1;P<z&&c>-1;){var M=W.Gj[c];B+=W.G?M.offsetWidth:M.offsetHeight;P++;c--}W.S4=B;z=Math;P=z.max;isNaN(W.e4)&&((B=W.S.Xv)?(c=g.dK("SPAN"),g.m0(c,"\u2013".repeat(B)),g.vs(c,XXf(W,W.S.oO)),W.K.appendChild(c),W.e4=c.offsetWidth,W.K.removeChild(c)):W.e4=0);B=W.K;W.i9=P.call(z,W.e4,W.Mj,(W.G?B.offsetHeight:B.offsetWidth)+1)},E5F=function(W,z){JRD(W);
var P=W.Gj.reduce((B,c)=>(W.G?c.offsetWidth:c.offsetHeight)+B,0);
P=W.S4-P;if(P!==W.Vf){const B=P>0&&W.Vf===0,c=P<W.Vf;z||isNaN(P)||B||!c||(g.dW(W.element,"ytp-rollup-mode"),W.gj(W.element,"transitionend",W.tp));g.vs(W.K,"transform",U6y(W,P));W.Vf=P}JRD(W)},Cxe=function(W,z,P,B){const {formatId:c,
PF:M,startTimeMs:t,durationMs:q}=W.G(z),w={formatId:c,startTimeMs:t,durationMs:q,XZ:M,Ey:M};let y=VX7(W.nT,w.startTimeMs);const L=y>=0?W.nT[y]:null,k=L?L.startTimeMs+L.durationMs:0,d=w.startTimeMs+w.durationMs;!L||w.startTimeMs-k>W.L?W.nT.splice(y+1,0,w):(L.durationMs=Math.max(k,d)-L.startTimeMs,L.Ey=Math.max(L.Ey,w.Ey));B(W.nT);B=g.PA(z);W=W.K;B=B.buffer.slice(B.byteOffset,B.byteLength+B.byteOffset);z=z.info.N;W.U?W.J==null?g.Nc(W.logger,350058965,"Null loaded track meta data at captions data received"):
P.rR(B,W.J,z*1E3):g.Nc(W.logger,350058965,"Null Representation at captions data received")},uL7=function(W,z){W.B=(P,B)=>{if(W.Z.C().experiments.cF("html5_sabr_live_support_subfragmented_captions"))(W.S?W.S=W.S.G(P):(W.S=P,T6D(W.S)),W.S)?P.info.yO&&(ARe(W.S),Cxe(W,W.S,z,B),W.S=null):g.Nc(W.logger,350058965,"Empty slice");
else if(P.info.yO){var c=P;if(W.Nn.length>0){for(c=W.Nn.shift();W.Nn.length>0;)c=c.G(W.Nn.shift());c=c.G(P)}c?(T6D(c),ARe(c),Cxe(W,c,z,B)):g.Nc(W.logger,350058965,"Empty slice")}else W.Nn.push(P)};
W.Z.addEventListener("sabrCaptionsDataLoaded",W.B)},VX7=function(W,z){W=g.Bv(W,{startTimeMs:z},(P,B)=>P.startTimeMs-B.startTimeMs);
return W>=0?W:-W-2},T6D=function(W){let z;
try{z=g.t$(W)*1E3}catch(P){z=W.info.startTime*1E3}z<0&&(z=W.info.startTime*1E3);W.info.startTime=z/1E3;W.info.N=z/1E3},ARe=function(W){let z;
try{z=g.kb(W)*1E3}catch(P){z=W.info.duration*1E3}z<0&&(z=W.info.duration*1E3);W.info.duration=z/1E3;W.info.A=z/1E3},Gcy=function(W,z){if(!g.Ra(W)||W.S!=null&&g.M3(z,W.S)&&W.S.S.rawcc!=null)return!1;
z=!!W.S&&W.S.isManifestless&&Object.values(W.S.S).some(P=>g.tp(P,"386"));
W=!!W.S&&!W.S.isManifestless&&g.Z7(W.S);return z||W},N6Y=function(W,z,P){const B=[];
for(const c in W.B.S){if(!W.B.S.hasOwnProperty(c))continue;const M=W.B.S[c];if(g.tp(M,P||null)){const t=M.info.captionTrack;t&&t.languageCode===z&&B.push(M)}}return B.length?B[0]:null},fqY=function(W,z){const P=[];
for(const c in W.B.S){if(!W.B.S.hasOwnProperty(c))continue;var B=W.B.S[c];if(g.tp(B,z||null)){let M=B.info.id,t=M,q=`.${M}`,w="",y="";if(B=B.info.captionTrack)M=B.languageCode,t=B.displayName,q=B.vssId,w=B.kind,y=B.id;P.push(new g.VV({id:c,languageCode:M,languageName:t,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:q,kind:w,captionId:y}))}}return P},zzk=function(W){const z=WCD.length;
if(W.byteLength<z)return!1;W=new Uint8Array(W,0,z);for(let P=0;P<z;P++)if(WCD[P]!==W[P])return!1;return!0},A9=function(W){W=W.split(":");
let z=0;for(const P of W)z=z*60+Number(P);return z*1E3},PGO=function(W,z,P,B){B=Object.assign({d8:0},B);
return new QC(W,z,P,"_"+bs++,B)},BYv=function(W,z,P,B,c,M,t,q,w){switch(t.tagName){case "b":q.bold=!0;
break;case "i":q.italic=!0;break;case "u":q.underline=!0}for(let L=0;L<t.childNodes.length;L++){var y=t.childNodes[L];if(y.nodeType===3)y=new eu(z,P,B,c.id,y.nodeValue,M||L>0,g.UL(q)?void 0:q),w.push(y),c.S.push(y);else{const k={};Object.assign(k,q);BYv(W,z,P,B,c,!0,y,k,w)}}},M2n=function(W,z,P){if(typeof z==="string"||H1y(z))return[{trackData:z,
cX:P}];if(typeof z==="string"&&z.substring(0,6)==="WEBVTT"||typeof z!=="string"&&zzk(z))return[{trackData:z,cX:P}];const B=new DataView(z);if(B.byteLength<=8||B.getUint32(4)!==1718909296)return[];var c=g.$s(B);if(W.h7&&c){var M=g.y_(c),t=g.ks(c);c=c.segmentNumber;M&&c&&W.h7.q4(c,M,t)}W=g.Zy(B,1835295092);if(!W||!W.length||!W[0].size)return[];M=[];for(t=0;t<W.length;t++)c=W[t],c=new Uint8Array(z,c.dataOffset,c.size-(c.dataOffset-c.offset)),c=g.Ai(c),M.push({trackData:c,cX:P+t*1E3});ctG(B,M,P);return M=
M.filter(q=>!!q.trackData)},qHD=function(W,z,P){W.S||(W.S=new t2f);
W=W.S.N(z,P);Math.random()<.01&&g.E0(Error("Deprecated subtitles format in web player: WebVTT"));return W},ctG=function(W,z,P){var B=g.SA(W,0,1836476516);
let c=9E4;B&&(c=g.mq(B)||9E4);B=0;const M=g.Zy(W,1836019558);for(let q=0;q<M.length;q++){var t=M[q];q<z.length&&(t=g.SA(W,t.dataOffset,1953653094))&&(t=g.SA(W,t.dataOffset,1952867444))&&(t=g.Ys(t)/c*1E3,q===0&&(B=t),z[q].cX=t-B+P||P*q*1E3)}},wKH=function(W){const z={};
if(W=g.nn(W))z.lang=W,g.qIY.test(W)&&(z.E7=1);return z},odG=function(W){const z=!!W.Z.NO()?.e4();
return W.N==="HLS"&&z?!0:W.m7&&z&&W.N!=="LIVE"&&W.N!=="SABR_LIVE"},us=function(W,z,P=!1){var B=W.D.Y("enable_player_captions_new_style_defaults")?ytf:k7o;
const c=B.oO;W.G={};Object.assign(W.G,B);W.G.oO={};Object.assign(W.G.oO,c);W.K={oO:{}};var M=z.backgroundOverride?W.K:W.G,t=z.background||c.background;J9.test(t);M.oO.background=t;M=z.colorOverride?W.K:W.G;t=z.color||c.color;J9.test(t);M.oO.color=t;M=z.windowColorOverride?W.K:W.G;t=z.windowColor||B.windowColor;J9.test(t);M.windowColor=t;M=z.backgroundOpacityOverride?W.K:W.G;t=z.backgroundOpacity;t==null&&(t=c.backgroundOpacity);M.oO.backgroundOpacity=t;M=z.fontSizeIncrementOverride?W.K:W.G;t=z.fontSizeIncrement;
t==null&&(t=c.fontSizeIncrement);M.oO.fontSizeIncrement=t;t=z.fontStyleOverride?W.K:W.G;M=z.fontStyle;M==null&&(M=c.bold&&c.italic?3:c.bold?1:c.italic?2:0);t=t.oO;switch(M){case 1:t.bold=!0;delete t.italic;break;case 2:delete t.bold;t.italic=!0;break;case 3:t.bold=!0;t.italic=!0;break;default:delete t.bold,delete t.italic}M=z.textOpacityOverride?W.K:W.G;t=z.textOpacity;t==null&&(t=c.textOpacity);M.oO.textOpacity=t;M=z.windowOpacityOverride?W.K:W.G;t=z.windowOpacity;t==null&&(t=B.windowOpacity);M.windowOpacity=
t;B=z.charEdgeStyleOverride?W.K:W.G;M=z.charEdgeStyle;M==null&&(M=c.charEdgeStyle);B.oO.charEdgeStyle=M;B=z.fontFamilyOverride?W.K:W.G;M=z.fontFamily;M==null&&(M=c.fontFamily);B.oO.fontFamily=M;W.loaded&&W.j4();P&&g.zu("yt-player-caption-display-settings",z,2592E3)},GG=function(W,z,P){z&&!W.X?(z=IqH({E7:0,
lang:"en"}),W.X=[z,new eu(z.start,z.end-z.start,0,z.id,P??"Captions look like this")],W.player.Ql(W.X)):!z&&W.X&&(LCY(W,W.X),W.X=null)},gd2=function(W){if(!W.Z.isInline())return g.PY("yt-player-sticky-caption")},Ns=function(W){if(!W.D.Y("enable_player_captions_persistence_state_machine")){var z=void 0,P=g.Q9().Jp(65);
if(g.C_(W.D)&&P!=null){if(gd2(W)!=null)return!1;z=!P}return z}},dOH=function(W){if(W.D.RD===1||W.videoData.sU===1||g.lr(W.videoData,"yt:cc")==="alwayson")return!0;
let z;W.videoData.captionTracks.length&&(z=W.getAudioTrack().B);if(W.D.Y("enable_player_captions_persistence_state_machine")){var P=W.D.Y("enable_player_captions_persistence_state_machine")?g.PY("yt-player-caption-persistence"):void 0;if(P!==void 0)return!!P}else if(W.D.RD===2){if(g.C_(W.D))P=gd2(W);else if(W.storage)try{P=W.storage.get("module-enabled")}catch(c){W.storage.remove("module-enabled")}else P=null;if(P!=null)return!!P}P=ZH(W.player.getAudioTrack(),g.C_(W.D));const B=g.lr(W.videoData,"yt:cc");
if(Ns(W)===void 0){if(P==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return B?B==="on":!0;if(P==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return B==="on"}else return B==="on";return z==="ON"||g.lr(W.videoData,"yt:cc")==="on"},fR=function(W,z=!1){if(W.B&&!z||!W.videoData.captionTracks.length)return!1;
W=W.getAudioTrack();return!!W.S||W.B==="FORCED_ON"},XK7=function(W){return W.D.Y("html5_honor_caption_availabilities_in_audio_track")&&W.N!=="LIVE"&&W.N!=="SABR_LIVE"},iOD=function(W,z){if(W.B){var P=W.Z.NO().Ws().textTracks,B=null;
W.N==="HLS"?B=W.B.getId():B=W.B.toString();for(let M=0;M<P.length;M++){var c=P[M];c.id===B&&(z?c.mode!=="showing"&&(c.mode="showing",c=W.B,W.E9(c,!!c,WP(W)?"g":W.J?"m":"s")):c.mode==="showing"&&(c.mode="disabled"))}}},WP=function(W){const z=zI(W);
return!!z&&W.B===z},SHv=function(W,z){if(W.N==="HLS")return!1;
g.jb(W.videoData)&&(z=!0);z||(z=W.N==="TTS"?!1:W.N==="INNERTUBE"?!1:!0);return z||W.D.Y("web_watch_disable_account_level_captions_settings")&&g.C_(W.D)?!0:!!g.Q9().Jp(66)},zI=function(W){return W.O&&W.O.S},PP=function(W,z){if(!W.S)return null;
if(W.O&&W.O.L)return W.O.L;z=SHv(W,z);z=W.S.S.S(z);let P=null;if(GL2(W.D)){var B=W.Z.isInline()?void 0:g.PY("yt-player-caption-sticky-language");var c=[B,W.videoData.captionsLanguagePreference,W.D.captionsLanguagePreference,g.lr(W.videoData,"yt:cc_default_lang")];let q=!1;for(let w=0;w<c.length;w++){const y=c[w];if(y){q=!0;for(var M=0;M<z.length;M++)if(g.nn(z[M])===y)return z[M];for(M=0;M<z.length;M++)if(g.nn(z[M]).split("-")[0]===y.split("-")[0])return z[M]}}if(q&&W.S&&(c=W.S.O,c.length))for(var t of c)if(t.languageCode===
B){P=t;break}}else for(t=[W.videoData.captionsLanguagePreference,W.D.captionsLanguagePreference,g.lr(W.videoData,"yt:cc_default_lang")],B=0;B<t.length;B++)for(c=0;c<z.length;c++)if(g.nn(z[c])===t[B])return z[c];t=null;W.O&&W.O.N&&(t=W.O.N);t||(t=z.find(q=>q.isDefault)||null);
t||(t=z[0]||zI(W));t&&P&&g.nn(t).split("-")[0]!==P.languageCode.split("-")[0]&&(t=uQf(t,P));return t},qD=function(W,z,P){W.loaded&&W.unload();
P!=null&&(W.J=P,W.J&&(W.D.Y("enable_player_captions_persistence_state_machine")?BP(W,!!z):g.C_(W.D)?cP(W,!!z):MD(W,!!z)));z!==null||fR(W,!0)||W.E9(z,!!z,W.J?"m":"s");W.B=z;fR(W)&&(W.B=zI(W));t0(W,W.B??void 0);W.load()},BP=function(W,z){W.D.Y("enable_player_captions_persistence_state_machine")&&g.zu("yt-player-caption-persistence",z,3122064E3)},cP=function(W,z){W.Z.isInline()||g.zu("yt-player-sticky-caption",z,2592E3)},MD=function(W,z){if(W.storage)try{W.storage.set("module-enabled",z)}catch(P){}},
t0=function(W,z){W.D.Y("html5_modify_caption_vss_logging")&&(W.videoData.D5=z)},KCD=function(W,z){var P=W.S4[z.id];
P&&P.N!==z&&(P.dispose(),delete W.S4[z.id],P=null);P||(P=l6y(W,z))&&(W.S4[z.id]=P)},mO2=function(W,z){const P=z.windowId;
W.HF[P]||(W.HF[P]=[]);W.HF[P].push(z)},l6y=function(W,z){const P=DOv(W);
if(!P)return null;var B=W.B?g.nn(W.B):null;B&&g.qIY.test(B)&&(z.params.E7=1);var c=W.UB.getPlayerSize();B=c.height*W.U.height;c=c.width*W.U.width;W.D.playerStyle!=="google-live"||W.G.isDefault||Object.assign(z.params,W.G);switch(z.params.d8!=null?z.params.d8:z.S.length>1?1:0){case 1:return new OO2(z,W.G,W.K,P.width,P.height,c,B,W.D.experiments,W.qs.bind(W),W.Z);case 2:return new YHv(z,W.G,W.K,P.width,P.height,c,B,W.D.experiments,W.qs.bind(W),W.Z);default:return new w3(z,W.G,W.K,P.width,P.height,c,
B,W.D.experiments,W.qs.bind(W),W.Z)}},DOv=function(W){let z=W.UB.getVideoContentRect(!0).height,P=W.UB.getVideoContentRect(!0).width;
if(!z||!P)return null;z*=W.U.height;P*=W.U.width;return{width:P,height:z}},LCY=function(W,z){W.player.J$(z);
for(const P of z)g.Av(W.Gj,P);YW(W.e4)},nde=function(W,z){if(!W.S)return{};
if(z){g.UL(z)||W.V9(z.vss_id,"m");if(W.L&&W.N!=="HLS"||!g.Y7(z))return;if(g.UL(z)){qD(W,null,!0);return}let B;var P=W.S.S.S(!0);for(let c=0;c<P.length;c++){const M=P[c];M.languageCode!==z.languageCode||B&&(M.languageName!==z.languageName||(M.captionId||"")!==(z.captionId||"")||g.Y2(M)!==z.displayName)||(B=z.translationLanguage?uQf(M,z.translationLanguage):M)}W.Ua(z.position);!B||B===W.B&&W.loaded||(z=g.TY(),P=g.nn(B),z.length&&P===z[z.length-1]||(z.push(P),g.zu("yt-player-caption-language-preferences",
z)),GL2(W.D)&&!W.Z.isInline()&&g.zu("yt-player-caption-sticky-language",P,2592E3),qD(W,B,!0))}else return W.loaded&&W.B&&!WP(W)?nR(W.B):{};return""};
g.I8.prototype.q4=g.cG(119,function(W,z,P){this.B.set(W,{Nx:z,v3:P})});
g.p1.prototype.q4=g.cG(118,function(W,z,P){this.i9.q4(W,z,P)});
g.hp.prototype.O=g.cG(117,function(){this.mediaElement.O()});
g.sC.prototype.O=g.cG(116,function(){var W=g.Be(document,"track",void 0,this.S);for(let z=0;z<W.length;z++)g.lT(W[z])});
g.hp.prototype.YA=g.cG(115,function(){return this.mediaElement.YA()});
g.sC.prototype.YA=g.cG(114,function(){return!(!this.S.textTracks||!this.S.textTracks.addEventListener)});
g.hp.prototype.e4=g.cG(113,function(){return this.mediaElement.e4()});
g.sC.prototype.e4=g.cG(112,function(){return!!this.S.textTracks});
g.hp.prototype.S4=g.cG(111,function(W){this.mediaElement.S4(W)});
g.sC.prototype.S4=g.cG(110,function(W){for(let z=0;z<W.length;z++)this.S.appendChild(W[z])});
g.q6.prototype.V9=g.cG(46,function(W,z){this.app.C6().V9(W,z)});
g.M_.prototype.V9=g.cG(45,function(W,z){this.W.V9(W,z)});
g.O2.prototype.V9=g.cG(44,function(W,z){W=[W,z];g.Ba(this,g.Mm(this.provider),"cfi",W)});
g.jX.prototype.V9=g.cG(43,function(W,z){this.qoe&&this.qoe.V9(W,z)});
g.L5.prototype.V9=g.cG(42,function(W,z){this.vZ.V9(W,z)});
g.vX.prototype.V9=g.cG(41,function(){});
g.q6.prototype.E9=g.cG(40,function(W,z,P){this.app.C6().E9(W,z,P)});
g.M_.prototype.E9=g.cG(39,function(W,z,P){this.W.E9(W,z,P)});
g.O2.prototype.E9=g.cG(38,function(W,z,P){if(this.dj!==W||this.yT!==z)z=z==="rawcc"?"":z,P=[W,z,this.dj,P],g.Ba(this,g.Mm(this.provider),"cfs",P),this.dj=W,this.yT=z});
g.jX.prototype.E9=g.cG(37,function(W,z,P){this.qoe&&this.qoe.E9(W,z,P)});
g.L5.prototype.E9=g.cG(36,function(W,z,P){this.vZ.E9(W,z,P)});
g.vX.prototype.E9=g.cG(35,function(){});
g.jB.prototype.vn=g.cG(9,function(){return this.h7});
g.bx.prototype.vn=g.cG(8,function(){return this.C6().WG()});
g.q6.prototype.WG=g.cG(7,function(){return this.app.vn()});
g.M_.prototype.WG=g.cG(6,function(){return this.W.WG()});
g.L5.prototype.WG=g.cG(5,function(){return this.loader?.vn()||null});
g.vX.prototype.WG=g.cG(4,function(){return null});
g.TL.prototype.SO=g.cG(2,function(W){return(W=this.N(W))?W.S:0});
g.uh.prototype.SO=g.cG(1,function(){return 0});
var zPF=/#(.)(.)(.)/,W_y=/^#(?:[0-9a-f]{3}){1,2}$/i,yRD={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},ZOD=class{constructor(){this.N=[];this.B=[]}S(W){return W?this.B.concat(this.N):this.B}},oE=class extends g.x{constructor(W){super();this.WF=W;this.S=new ZOD;this.i9=new ZOD;this.G=null;this.O=[];this.S4=[]}A(){}L(){}N(){}K(){return""}EB(){return!1}P6(W,z){if(this.WF.C().Y("html5_dispatch_tracklist_loaded_event")){this.G&&(this.G.reject(),this.G=null);var P=[];this.WF.rj("trackListLoaded",
this.S,P,z);this.WF.C().Y("enable_po_decoration_of_forced_tracks")&&this.WF.rj("trackListLoaded",this.i9,P,z);P.length?(z=new g.Ws,z.promise.then(W.P6,()=>{}),this.G=z,Promise.all(P).then(z.resolve,z.reject).finally(()=>{this.G=null})):W.P6()}else W.P6()}xA(){this.G&&(this.G.reject(),this.G=null);
this.N();super.xA()}},j2G={en:"English"},FCv=class extends oE{constructor(W){super(W);this.B=new Set}L(W){var z=this.WF.NO();if(z&&z.Ws()){z=z.Ws().textTracks;for(const P of z)P.kind==="subtitles"&&!this.B.has(P.language)&&P.language&&($W(this.S,new g.VV({languageCode:P.language,languageName:P.language,kind:P.kind,id:P.id,displayName:j2G[P.label]||P.label,vss_id:`.${P.language}`})),this.B.add(P.language))}this.S.S().length>0&&W.P6()}},$OG=class extends oE{constructor(W,z,P){super(W);this.videoData=
z;this.audioTrack=P;this.B=null;this.J=!1;this.O=z.lc;this.S4=z.Gw;this.J=g.jb(z)}A(W,z,P){this.hp();z=this.K(W,z);const B=this.WF.C().Y("html5_report_captions_ctmp_qoe"),c=(0,g.C)();this.N();cRU(this,z,{format:"RAW",onSuccess:M=>{this.B=null;if(B){var t=(M.responseText.length/1024).toFixed();const q=(0,g.C)();this.videoData.j("capresp",{ms:q-c,kb:t})}t=M.getResponseHeader&&M.getResponseHeader("Content-Length")?Number(M.getResponseHeader("Content-Length")):0;P.rR(M.responseText,W,void 0,void 0,t)},
onError:B?M=>{this.videoData.j("capfail",{status:M?.status??0})}:void 0,
withCredentials:!0})}L(W){if(this.audioTrack){for(const z of this.audioTrack.captionTracks)$W(this.S,z);this.audioTrack.S&&$W(this.i9,this.audioTrack.S)}this.P6(W,this.videoData.videoId)}K(W,z){const P=W.nI(),B={fmt:z};if(z==="srv3"||z==="3"||z==="json3")g.w9()?Object.assign(B,{xorb:2,xobt:1,xovt:1}):Object.assign(B,{xorb:2,xobt:3,xovt:3});W.translationLanguage&&(B.tlang=g.nn(W));this.J&&(B.xosf="1");Object.assign(B,this.WF.C().S);return g.Lj(P,B)}N(){this.B&&this.B.abort()}},RzY=class{constructor(){this.segments=
[]}contains(W){W=g.Bv(this.segments,W);return W>=0||W<0&&(-W-1)%2===1}length(){return this.segments.length/2}},xOk=class extends g.x{constructor(W,z,P,B,c,M){super();this.policy=W;this.player=z;this.Ns=P;this.J=B;this.G=c;this.U=M;this.L=new RzY;this.K=-1;this.B=this.N=this.S=null;this.S4=0;this.A=new g.wW(this.O,1E3,this);this.events=new g.GL(this);g.v(this,this.A);g.v(this,this.events);this.events.gj(z,"SEEK_COMPLETE",this.X);this.X();this.O()}xA(){super.xA();this.B&&this.B.cancel()}X(){this.seekTo(this.player.getCurrentTime())}seekTo(W){W-=
this.player.e3();const z=this.S;this.S=g.px(this.Ns.K(W).b9);z!==this.S&&this.U&&this.U()}reset(){this.L=new RzY;this.K=-1;this.B&&(this.B.cancel(),this.B=null)}O(){this.hp();var W;if(W=this.S!=null)W=this.S,W=W.Ns.L(W);if(W&&!this.B&&!(this.S&&this.S.startTime-this.player.getCurrentTime()>30)){W=this.S;W=W.Ns.e4(W);const c=W.b9[0];if(this.player.getVideoData()?.enableServerStitchedDai){var z=this.player.WG();if(z){var P=c.Ns.info.id;const M=c.PF;var B=W.b9[0].N;if(this.policy.e4){if(z=g.dM(z,B,M,
P,3))W.L=z}else if(P=z.c5(B,M,P,3))if(B=2,z.Y5.has(M)?B=0:g.Mk(z,M)&&(B=1),z=B,z===0)P&&(W.S=new g.C6(P));else if(z===2){this.A.start();tXF(this)&&this.seekTo(this.player.getCurrentTime());return}}}c.Ns.index.DZ(c.PF)?(this.L.contains(W.b9[0].PF)||q2y(this,W),this.S=g.px(W.b9)):tXF(this)&&this.seekTo(this.player.getCurrentTime())}this.A.start()}},vdU=class extends oE{constructor(W,z){super(z);this.B=W;this.Z=z;this.J=null;this.X=!1;this.logger=new g.GT("caps");this.U=g.M3(this.Z,this.B)}A(W,z,P){this.N();
z=wXe(this,W.getId());z||(z=W.languageCode,z=this.B.isManifestless?o5Y(this,z,"386"):o5Y(this,z));if(z){var B=(z.index.SO(z.index.IL())-z.index.getStartTime(z.index.IL()))*1E3,c=new g.gpY(this.Z.C());this.J=new xOk(c,this.Z,z,(M,t)=>{P.rR(M,W,t,B)},this.U||g.z3(z.info),()=>{this.J&&this.J.reset();
this.X=!0})}}EB(){const W=this.X;
this.X=!1;return W}L(W){var z=this.Z.C().Y("html5_fallback_if_rawcc_missing");const P=this.B.S.rawcc!=null;if(!this.U||!P&&z)z=this.B.isManifestless?kcf(this,"386"):kcf(this);else{if(!P){g.Nc(this.logger,386248249,"rawcc used but unavailable");return}z=[new g.VV({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.VV({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const B of z)$W(this.S,
B);W.P6()}N(){this.J&&(this.J.dispose(),this.J=null)}K(){return""}},s2Y=class extends oE{constructor(W,z,P,B,c,M){super(W);this.videoId=P;this.X=c;this.eventId=M;this.U={};this.B=null;W=B||g.yR(z).hl||"";W=W.split("_").join("-");this.J=g.Lj(z,{hl:W})}A(W,z,P){this.hp();z=this.K(W,z);this.N();this.B=g.pj(z,{format:"RAW",onSuccess:B=>{this.B=null;const c=B.getResponseHeader&&B.getResponseHeader("Content-Length")?Number(B.getResponseHeader("Content-Length")):0;P.rR(B.responseText,W,void 0,void 0,c)},
withCredentials:!0})}L(W){let z=this.J;const P={type:"list",tlangs:1,v:this.videoId,vssids:1};this.X&&(P.asrs=1);z=g.Lj(z,P);this.N();this.B=g.pj(z,{format:"RAW",onSuccess:B=>{this.B=null;if((B=B.responseXML)&&B.firstChild){var c=B.getElementsByTagName("track");for(var M=0;M<c.length;M++){var t=c[M],q=t.getAttribute("lang_code");const w=t.getAttribute("lang_translated"),y=t.getAttribute("name"),L=t.getAttribute("kind"),k=t.getAttribute("id"),d=t.getAttribute("lang_default")==="true",X=t.getAttribute("cantran")===
"true";t=t.getAttribute("vss_id");$W(this.S,new g.VV({languageCode:q,languageName:w,name:y,kind:L,id:k,is_servable:!0,is_translateable:X,vss_id:t,is_default:d}))}B=B.getElementsByTagName("target");c=B.length;for(M=0;M<c;M++)q={languageCode:B[M].getAttribute("lang_code"),languageName:B[M].getAttribute("lang_translated"),languageOriginal:B[M].getAttribute("lang_original"),id:B[M].getAttribute("id"),isDefault:B[M].getAttribute("lang_default")==="true"},this.U[q.languageCode]=q.languageName,this.O.push(q)}this.P6(W,
this.videoId)},
withCredentials:!0})}K(W,z){let P=this.J;z={v:this.videoId,type:"track",lang:W.languageCode,name:W.getName(),kind:W.kind,fmt:z};const B=this.WF.C();B.Y("captions_url_add_ei")&&(z.ei=this.eventId);W.translationLanguage&&(z.tlang=g.nn(W));Object.assign(z,B.S);return P=g.Lj(P,z)}N(){this.B&&this.B.abort()}},J9=/^#(?:[0-9a-f]{3}){1,2}$/i;var rtF=["left","right","center","justify"];var w3=class extends g.jc{constructor(W,z,P,B,c,M,t,q,w,y){const L=y.isInline()&&!0,k={};Object.assign(k,z);Object.assign(k,W.params);Object.assign(k,P);const d={};Object.assign(d,z.oO);W.params.oO&&Object.assign(d,W.params.oO);Object.assign(d,P.oO);L&&(k.windowOpacity=.6,d.backgroundOpacity=0);k.oO=d;const X=k.E7===1,D=[{V:"span",Tj:"captions-text",zj:{style:"word-wrap: normal; display: block;"}}],R=q.cF("caption_edit_on_hover")&&y.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
R&&D.unshift({V:"button",Tj:"caption-edit",zj:{tabindex:"0","aria-label":Pxn()},o0:[{V:"svg",zj:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},o0:[{V:"path",zj:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({V:"div",Tj:"caption-window",zj:{id:`caption-window-${W.id}`,dir:X?"rtl":"ltr",tabindex:"0",lang:k.lang},o0:D});
this.J=[];this.YA=!1;this.N=W;this.m7=this.R0=null;this.Ta=M;this.O8=t;this.O=null;this.maxWidth=M*.96;this.maxHeight=t*.96;this.S=k;this.tT=P;this.EB=z;this.K=this.p6("captions-text");W=this.K.style;this.fK=q.cF("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in W||"WebkitBoxDecorationBreak"in W);this.qs=L_v(B,c,M,t);this.qO=w;R&&(this.A=this.p6("caption-edit"),this.gj(this.A,"click",()=>{this.qO()}));
this.type=0;this.j4=this.qs*g5f(d);this.d7=L;this.u9=q.cF("enable_centered_caption_for_tvfilm_video")&&y.getVideoData().isTvfilmVideo;this.U=y.C().f6().S.Jp(g.MTO);B=new g.$5(this.element,!0);g.v(this,B);B.subscribe("dragstart",this.fI,this);B.subscribe("dragmove",this.DB,this);B.subscribe("dragend",this.WM,this);this.yI=this.TB=this.Y6=this.m$=0;B="";this.S.windowOpacity&&(B=ju(this.S.windowColor),B="rgba("+B[0]+","+B[1]+","+B[2]+","+this.S.windowOpacity+")");c={"background-color":B,display:this.S.isVisible===
!1?"none":"","text-align":rtF[this.S.textAlign]};this.fK&&(c["border-radius"]=B?`${this.j4*.375}px`:"");(this.G=this.N.params.E7===2||this.N.params.E7===3)&&d6o(this,this.element);g.vs(this.element,c);L&&this.element.parentElement?.style.setProperty("--caption-window-color",B);switch(this.S.xm){case 0:case 1:case 2:g.dW(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.dW(this.element,"ytp-caption-window-bottom")}}fI(W,z){this.TB=W;this.yI=z;const P=g.aC(this.element,this.element.parentElement);
this.m$=W-P.x;this.Y6=z-P.y}DB(W,z){if(W!==this.TB||z!==this.yI){g.gW(this.element,"ytp-dragging")||g.dW(this.element,"ytp-dragging");var P=g.EV(this.element);W=W-this.m$-.02*this.Ta;var B=z-this.Y6-.02*this.O8,c=(W+P.width/2)/this.maxWidth*3;c=Math.floor(g.mh(c,0,2));var M=(B+P.height/2)/this.maxHeight*3;M=Math.floor(g.mh(M,0,2));z=c+M*3;W=(W+c/2*P.width)/this.maxWidth;W=g.mh(W,0,1)*100;P=(B+M/2*P.height)/this.maxHeight;P=g.mh(P,0,1)*100;this.N.params.xm=z;this.N.params.yS=P;this.N.params.xj=W;this.N.params.isDefault=
!1;this.S.xm=z;this.S.yS=P;this.S.xj=W;this.S.isDefault=!1;this.EB.xm=z;this.EB.yS=P;this.EB.xj=W;this.EB.isDefault=!1;this.zf()}}WM(){g.ik(this.element,"ytp-dragging")}zf(){this.X(this.J)}X(W){var z=this.d7?0:Math.min(this.OJ(),this.maxWidth),P=this.WZ(),B=this.d7;if(B){var c=getComputedStyle(this.K.parentNode);c=xW(c.borderLeftWidth)+xW(c.borderRightWidth)+xW(c.paddingLeft)+xW(c.paddingRight)}else c=0;const M=c;c="";this.N.params.E7===3&&(c="rotate(180deg)");var t=B?`calc(96% - ${M}px)`:"96%";g.vs(this.element,
{top:0,left:0,right:"",bottom:"",width:z?`${z}px`:"",height:P?`${P}px`:"","max-width":t,"max-height":t,margin:"",transform:""});this.dj(W);c={transform:c,top:"",left:"",width:z?`${z}px`:"",height:P?`${P}px`:"","max-width":"","max-height":""};t=this.S.xm;var q=this.S.xj;const w=this.S.yS;this.u9&&t!=null&&(q=50,t=Math.floor(t/3)*3+1);q=q*.96+2;switch(t){case 0:case 3:case 6:(B=this.S.oO.fontSizeIncrement)&&B>0&&this.S.E7!==2&&this.S.E7!==3&&(q=Math.max(q/(1+B*2),2));c.left=`${q}%`;break;case 1:case 4:case 7:c.left=
`${q}%`;q=0;this.U||(q=this.K.offsetWidth);z||q?(z=z||q+1,c.width=`${z}px`,c["margin-left"]=B?`${z/-2-M/2}px`:`${z/-2}px`):(this.U&&(c.width="max-content"),c.transform+=" translateX(-50%)");break;case 2:case 5:case 8:c.right=`${100-q}%`}B=w*.96+2;switch(t){case 0:case 1:case 2:c.top=`${B}%`;break;case 3:case 4:case 5:c.top=`${B}%`;B=0;this.U||(B=this.element.clientHeight);(P=P||B)?(c.height=`${P}px`,c["margin-top"]=`${P/-2}px`):c.transform+=" translateY(-50%)";break;case 6:case 7:case 8:c.bottom=
`${100-B}%`}g.vs(this.element,c);if(this.A){if(this.U)P=this.j4;else{if(this.u9&&W.length===0)W=0;else{P=1;for(B=0;B<W.length;B++)c=W[B],typeof c.text==="string"&&(P+=c.text.split("\n").length-1,c.append||B===0||P++);W=P}P=this.u9?W>0?this.K.offsetHeight/W:0:this.K.offsetHeight/W}this.A.style.height=`${P}px`;this.A.style.width=`${P}px`;this.element.style.paddingLeft=`${P+5}px`;this.element.style.paddingRight=`${P+5}px`;this.U||(W=Number(this.element.style.marginLeft.replace("px",""))-P-5,P=Number(this.element.style.marginRight.replace("px",
""))-P-5,this.element.style.marginLeft=`${W}px`,this.element.style.marginRight=`${P}px`)}}dj(W){let z;for(z=0;z<W.length&&W[z]===this.J[z];z++);if(this.YA||this.J.length>z)z=0,this.YA=!1,this.J=[],this.O=this.m7=this.R0=null,g.iT(this.K);for(;z<W.length;z++)lq2(this,W[z])}OJ(){return 0}WZ(){return 0}toString(){return super.toString()}};var pKo=class{constructor(){this.N=this.time=this.mode=this.B=0;this.L=new I6G(this);this.G=new I6G(this);this.S=[];this.clear()}clear(){this.N=this.time=this.mode=0;this.S=[];this.reset()}reset(){this.mode=0;this.L.reset(0);this.G.reset(1)}},K_7=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],hzH=class{constructor(){this.type=0}set(W){this.type=W}get(){return this.type}},ezY=class{constructor(){this.state=this.Zy=this.Xq=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Lm(){return this.state!==0}matches(W,z){return this.Lm()&&W===this.Xq&&z===this.Zy}},bOy=class{constructor(){this.timestamp=this.S=0}reset(){this.timestamp=
this.S=0}},ya=class{constructor(W){this.G=W;this.N=[];this.S=this.B=this.row=0;this.style=new hzH;this.L=0;for(W=0;W<=15;W++){this.N[W]=[];for(let z=0;z<=32;z++)this.N[W][z]=new bOy}}updateTime(W){for(let z=1;z<=15;++z)for(let P=1;P<=32;++P)this.N[z][P].timestamp=W}debugString(){let W="\n";for(let z=1;z<=15;++z){for(let P=1;P<=32;++P){const B=this.N[z][P];W=B.S===0?W+"_":W+String.fromCharCode(B.S)}W+="\n"}return W}reset(W){for(let z=0;z<=15;z++)for(let P=0;P<=32;P++)this.N[z][P].reset();this.L=W;
this.S=0;this.B=this.row=1}},n5H=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Z1H=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],j87=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],F_F=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],Q2k=class{constructor(W){this.N=W;this.G=0;this.style=new hzH;this.K=new ya(this.N);this.A=new ya(this.N);this.text=new ya(this.N);this.B=this.K;this.L=this.A;this.S=this.B}reset(W,z){this.G=z;this.style.set(2);this.B=this.K;this.L=this.A;this.S=this.B;const P=(W<<2)+(z<<1);this.K.reset(P);this.A.reset(P);
this.text.reset((W<<2)+(z<<1)+1)}},I6G=class{constructor(W){this.S=W;this.G=0;this.N=new Q2k(this.S);this.K=new Q2k(this.S);this.B=new ezY;this.L=this.N}reset(W){this.G=W;this.B.clear();this.L=this.N;this.N.reset(W,0);this.K.reset(W,1)}};var a6Y=class{L(){}};var eu=class extends g.bd{constructor(W,z,P,B,c,M=!1,t=null){super(W,W+z,{priority:P,namespace:"captions"});this.windowId=B;this.text=c;this.append=M;this.S=t}toString(){return super.toString()}};var k1=class extends g.x{reset(){}};var QC=class extends g.bd{constructor(W,z,P,B,c){super(W,W+z,{priority:P,namespace:"captions"});this.id=B;this.params=c;this.S=[]}toString(){return super.toString()}},bs=0;var HOo=class extends k1{constructor(W){super();this.L=W;this.pens={};this.J={};this.O={};this.G="_"+bs++;this.A={};this.B=this.S=null;this.K=!0}reset(){this.A={};this.B=this.S=null;this.K=!0}N(W,z){W=W.firstChild;W.getAttribute("format");z=z||0;Number.isFinite(z);W=Array.from(W.childNodes);for(var P of W)if(P.nodeType===1)switch(P.tagName){case "head":var B=P;break;case "body":var c=P}if(B){B=Array.from(B.childNodes);for(var M of B)if(M.nodeType===1)switch(M.tagName){case "pen":P=M.getAttribute("id");
B=this.pens;W={};var t=M.getAttribute("p");t&&Object.assign(W,this.pens[t]);t=HE(M,"b");t!=null&&(W.bold=t);t=HE(M,"i");t!=null&&(W.italic=t);t=HE(M,"u");t!=null&&(W.underline=t);t=UO(M,"et");t!=null&&(W.charEdgeStyle=t);t=UO(M,"of");t!=null&&(W.offset=t);t=EO(M,"bc");t!=null&&(W.background=t);t=EO(M,"ec");t!=null&&(W.Kx=t);t=EO(M,"fc");t!=null&&(W.color=t);t=UO(M,"fs");t!=null&&t!==0&&(W.fontFamily=t);t=au(M,"sz");t!==void 0&&(W.fontSizeIncrement=t/100-1);t=au(M,"bo");t!==void 0&&(W.backgroundOpacity=
t/255);t=au(M,"fo");t!==void 0&&(W.textOpacity=t/255);t=UO(M,"rb");t!=null&&t!==10&&t!==0&&(W.sy=t>10?t-1:t);t=UO(M,"hg");t!=null&&(W.A1=t);B[P]=W;break;case "ws":B=M.getAttribute("id");this.O[B]=pXo(this,M);break;case "wp":B=M.getAttribute("id"),this.J[B]=hPH(this,M)}}if(c){M=[];c=Array.from(c.childNodes);for(R of c)if(R.nodeType===1)switch(R.tagName){case "w":this.S=ePv(this,R,z,!1);(c=this.A[this.S.id])&&c.end>this.S.start&&(c.end=this.S.start);this.A[this.S.id]=this.S;M.push(this.S);break;case "p":var q=
R;W=z;c=[];B=q.getAttribute("w")||this.G;P=!!HE(q,"a");W=(au(q,"t")||0)+W;t=au(q,"d")||5E3;P||(!this.K&&this.B&&this.B.windowId===B&&this.B.end>W&&(this.B.end=W),this.B&&this.B.text==="\n"&&(this.B.text=""));const I=P?6:5;var w=q.getAttribute("p");w=w?this.pens[w]:null;const e=Array.from(q.childNodes);e.length&&(this.K=q.getAttribute("d")!=null);for(q=0;q<e.length;q++){var y=e[q],L=void 0;q>0&&(P=!0);let b;y.nodeType===1&&(b=y);if(b&&b.tagName==="s"){if((y=(y=b.getAttribute("p"))?this.pens[y]:null)&&
y.sy&&(y.sy===1?(y=e.slice(q,q+4),y.length===4&&(L=rRk(W,t,B,P,I,y,this.pens),q+=3)):L=rRk(W,t,B,P,I,[b],this.pens)),!L){var k=b;L=W;y=t;var d=B,X=P;const a=k.textContent?k.textContent:"";var D=k.getAttribute("p");D=D?this.pens[D]:null;k=au(k,"t")||0;L=new eu(L+k,y-k,I,d,a,X,D)}}else L=new eu(W,t,I,B,y.textContent||"",P,w);c.push(L);this.B=L}if(c.length>0){c[0].windowId===this.G&&(this.S=ePv(this,R,z,!0),M.push(this.S));for(const b of c)b.windowId=this.S.id,this.S.S.push(b),M.push(b)}}var R=M}else R=
[];return R}};var UOk=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),JtH=class extends k1{constructor(W){super();this.K=W;this.S=new Map;this.L=new Map;this.G=new Map;this.B=new Map}reset(){this.B.clear()}N(W,z){W=JSON.parse(W);if(!W)return[];if(W.pens){var P=W.pens,B=0;for(var c of P){P={};var M=c.pParentId;M&&Object.assign(P,this.S.get(M));c.bAttr&&(P.bold=!0);c.iAttr&&(P.italic=!0);c.uAttr&&(P.underline=!0);M=c.ofOffset;M!=null&&(P.offset=M);c.szPenSize!==void 0&&(P.fontSizeIncrement=c.szPenSize/100-1);
M=c.etEdgeType;M!=null&&(P.charEdgeStyle=M);c.ecEdgeColor!==void 0&&(P.Kx=VC(c.ecEdgeColor));M=c.fsFontStyle;M!=null&&M!==0&&(P.fontFamily=M);c.fcForeColor!==void 0&&(P.color=VC(c.fcForeColor));c.foForeAlpha!==void 0&&(P.textOpacity=c.foForeAlpha/255);c.bcBackColor!==void 0&&(P.background=VC(c.bcBackColor));c.boBackAlpha!==void 0&&(P.backgroundOpacity=c.boBackAlpha/255);(M=c.rbRuby)&&M!==10&&(P.sy=M>10?M-1:M,P.textEmphasis=UOk.get(P.sy));c.hgHorizGroup&&(P.A1=c.hgHorizGroup);this.S.set(B++,P)}}if(W.wsWinStyles){B=
W.wsWinStyles;c=0;for(var t of B)B={},(P=t.wsParentId)?Object.assign(B,this.G.get(P)):Object.assign(B,this.K),t.mhModeHint!==void 0&&(B.d8=t.mhModeHint),t.juJustifCode!==void 0&&(B.textAlign=t.juJustifCode),t.pdPrintDir!==void 0&&(B.E7=t.pdPrintDir),t.sdScrollDir!==void 0&&(B.jb=t.sdScrollDir),t.wfcWinFillColor!==void 0&&(B.windowColor=VC(t.wfcWinFillColor)),t.wfoWinFillAlpha!==void 0&&(B.windowOpacity=t.wfoWinFillAlpha/255),this.G.set(c++,B)}if(W.wpWinPositions){c=W.wpWinPositions;t=0;for(var q of c)c=
{},(B=q.wpParentId)&&Object.assign(c,this.L.get(B)),q.ahHorPos!==void 0&&(c.xj=q.ahHorPos),q.apPoint!==void 0&&(c.xm=q.apPoint),q.avVerPos!==void 0&&(c.yS=q.avVerPos),q.ccCols!==void 0&&(c.Xv=q.ccCols),q.rcRows!==void 0&&(c.ow=q.rcRows),this.L.set(t++,c)}if(W.events){W=W.events;q=[];for(const U of W)if(t=(U.tStartMs||0)+z,c=U.dDurationMs||0,U.id)B=String(U.id),W=b1U(this,U,t,c,B),q.push(W),this.B.set(B,W);else{U.wWinId?B=U.wWinId.toString():(B="_"+bs++,W=b1U(this,U,t,c,B),q.push(W),this.B.set(B,W));
W=q;var w=U;c===0&&(c=5E3);P=this.B.get(B);const zU=(M=!!w.aAppend)?6:5,go=w.segs;let oy=null;w.pPenId&&(oy=this.S.get(w.pPenId));for(w=0;w<go.length;w++){var y=go[w],L=y.utf8;if(L){var k=y.tOffsetMs||0;let n2=null;y.pPenId&&(n2=this.S.get(y.pPenId));if((P.params.d8!=null?P.params.d8:P.S.length>1?1:0)===2&&M&&L==="\n")continue;y=null;var d=[],X;if(X=n2&&n2.sy===1)a:{X=go;var D=w;if(D+3>=X.length||!X[D+1].pPenId||!X[D+2].pPenId||!X[D+3].pPenId){X=!1;break a}var R=X[D+1].pPenId;(R=this.S.get(R))&&R.sy&&
R.sy===2?(R=X[D+2].pPenId,R=this.S.get(R),!R||!R.sy||R.sy<3?X=!1:(R=X[D+3].pPenId,X=(R=this.S.get(R))&&R.sy&&R.sy===2?!0:!1)):X=!1}if(X)k=go[w+1].utf8,y=go[w+3].utf8,X=go[w+2].utf8,D=this.S.get(go[w+2].pPenId),L=s8o(L,k,X,y,D),y=new eu(t,c,zU,B,L,M,n2),w+=3;else{if(L.indexOf("<")>-1){d=n2;X=oy;D=t;R=c;var I=k,e=zU,b=M;const GU=[];var a=Ru(`<html>${L}</html>`);if(!a.getElementsByTagName("parsererror").length&&a.firstChild?.childNodes.length)for(const UY of a.firstChild.childNodes){a=UY.textContent?.replace(/\n/g,
"")??"";if(UY.nodeType===3&&(!a||a.match(/^ *$/)!=null))continue;const yr={};Object.assign(yr,d||X);switch(UY?.tagName){case "b":yr.bold=!0;break;case "i":yr.italic=!0;break;case "u":yr.underline=!0}GU.push(new eu(D+I,R-I,e,P.id,a,b,yr))}d=GU}d.length||(d=[new eu(t+k,c-k,zU,P.id,L,M,n2||oy)])}if(d.length)for(const GU of d)W.push(GU),P.S.push(GU);else y&&(W.push(y),P.S.push(y))}M=!0}}z=q}else z=[];return z}};var Edk=class extends oE{constructor(W,z,P){super(W);this.videoData=z;this.audioTrack=P;this.O=z.lc}A(W,z,P){fJF(this.videoData.videoId,W.vssId,P.rR)}L(W){if(this.audioTrack)for(const z of this.audioTrack.captionTracks)$W(this.S,z);W.P6()}};var OO2=class extends w3{constructor(W,z,P,B,c,M,t,q,w,y){super(W,z,P,B,c,M,t,q,w,y);this.type=1}dj(W){const z=this.N.S;super.dj(W);let P,B;for(W=W.length;W<z.length;W++){const c=z[W];let M;B&&c.S===P?M=B:(M={},Object.assign(M,c.S),Object.assign(M,V2O),P=c.S,B=M);lq2(this,c,M)}}},V2O={Dv:!0};var Q8O=class extends a6Y{constructor(W,z){super();this.trackData=W;this.K=z;this.version=this.G=this.N=this.byteOffset=0;this.B=[];this.S=new DataView(this.trackData)}L(W,z,P,B,c){if(P<B){const M="_"+bs++;P=P/1E3-this.K;B=B/1E3-this.K;W=new QC(P,B-P,5,M,{textAlign:0,xm:0,xj:z*2.5,yS:W*5.33});c=new eu(P,B-P,5,M,c);this.B.push(W);this.B.push(c)}}},CGU=class extends k1{constructor(W,z){super();this.B=W;this.L=z;this.track=this.L.languageName==="CC3"?4:0;this.S=new pKo;this.S.B=1<<this.track}N(W){W=
new Q8O(W,this.B);if(aq7(W)){for(;W.byteOffset<W.S.byteLength;)for(W.version===0?W.N=TG(W)*(1E3/45):W.version===1&&(W.N=TG(W)*4294967296+TG(W)),W.G=CR(W);W.G>0;W.G--){var z=CR(W);const P=CR(W),B=CR(W);z&4&&(z&3)===this.track&&(this.track===0||this.track===1)&&(z=this.S,z.S.push({time:W.N,type:this.track,gT:P,BV:B,order:z.S.length}))}Y2n(this.S,W);return W.B}return[]}reset(){this.S.clear()}};var YHv=class extends w3{constructor(W,z,P,B,c,M,t,q,w,y){super(W,z,P,B,c,M,t,q,w,y);this.type=2;this.Gj=[];this.i9=this.S4=this.Vf=0;this.e4=NaN;this.Mj=0;this.Og=null;this.mj=new g.wW(this.tp,433,this);this.A&&(y.createClientVe(this.A,this,167342),this.gj(this.A,"click",()=>{y.logClick(this.A)}),W=new g.$5(this.element,!0),g.v(this,W),W.subscribe("hoverstart",()=>{y.logVisibility(this.A,!0)},this));
g.dW(this.element,"ytp-caption-window-rollup");g.v(this,this.mj);g.vs(this.element,"overflow","hidden")}zf(){var W=this.mj;W.stop();W.YN()}tp(){this.element.removeEventListener("transitionend",this.tp,!1);g.ik(this.element,"ytp-rollup-mode");this.X(this.Og,!0)}WZ(){return this.G?this.i9:this.S4}OJ(){return this.G?this.S4:this.i9}X(W,z){this.Og=W;if(this.N.params.ow){var P=0;for(let B=0;B<this.J.length&&P<W.length;B++)this.J[B]===W[P]&&P++;P>0&&P<W.length&&(W=this.J.concat(W.slice(P)));this.Mj=this.i9;
this.S4=this.i9=0;super.X(W);E5F(this,z)}super.X(W)}};var Ate=class{constructor(W,z,P,B){this.Z=W;this.K=z;this.logger=P;this.LT=B;this.nT=[];this.S=null;this.N=[];this.Nn=[];this.B=null;W=g.my(this.Z.C().experiments,"html5_override_micro_discontinuities_threshold_ms");this.L=W>0?W:10}unload(){this.B!=null&&(this.Z.removeEventListener("sabrCaptionsDataLoaded",this.B),this.B=null);this.nT=[];this.S=null;this.N=[];this.Z.rj("sabrCaptionsBufferedRangesUpdated",this.nT)}G(W){return{formatId:g.iW(W.info.Ns.info,this.LT),PF:W.info.PF+(this.LT?0:1),startTimeMs:W.info.N*
1E3,durationMs:W.info.A*1E3}}};var uWo=class extends oE{constructor(W,z){super(z);this.B=W;this.Z=z;this.logger=new g.GT("caps");this.J=this.U=null;this.X=new Ate(this.Z,this,this.logger,this.B.LT)}A(W,z,P){this.N();z=W.getId();z=z!=null&&z in this.B.S?this.B.S[z]:null;z||(z=W.languageCode,z=this.B.isManifestless?N6Y(this,z,"386"):N6Y(this,z));z&&(this.J=W,this.U=z,uL7(this.X,P),this.Z.rj("sabrCaptionsTrackChanged",g.iW(z.info,this.B.LT)))}L(W){var z=this.B.isManifestless?fqY(this,"386"):fqY(this);for(const P of z)$W(this.S,P);
W.P6()}N(){this.J&&(this.J=this.U=null,this.X.unload(),this.Z.rj("sabrCaptionsTrackChanged",null))}K(){return""}};var WCD="WEBVTT".split("").map(W=>W.charCodeAt(0)),t2f=class extends k1{constructor(){super()}N(W,z){W instanceof ArrayBuffer&&(W=g.Ai(new Uint8Array(W)));
const P=[];W=W.split(G7F);for(let D=1;D<W.length;D++){var B=W[D],c=z;if(B!==""&&!NY7.test(B)){var M=LM.exec(B);if(M&&M.length>=4){var t=A9(M[1]),q=A9(M[2])-t;t+=c;var w=(M=M[3])?M.split(" "):[];M={};var y=null;var L="";var k=null,d="";for(const R of w){w=R.split(":");if(w.length!==2)continue;var X=w[1];switch(w[0]){case "line":w=X.split(",");w[0].endsWith("%")&&(y=w[0],M.yS=Number.parseInt(y,10),w.length===2&&(L=w[1].trim()));break;case "position":w=X.split(",");k=w[0];M.xj=Number.parseInt(k,10);
w.length===2&&(d=w[1].trim());break;case "align":switch(X){case "start":M.textAlign=0;break;case "middle":M.textAlign=2;break;case "end":M.textAlign=1}}}y||L||(L="end");if(!k)switch(M.textAlign){case 0:M.xj=0;break;case 1:M.xj=100;break;case 2:M.xj=50}if(M.textAlign!=null){y=0;switch(L){case "center":y+=3;break;case "end":y+=6;break;default:y+=0}switch(d){case "line-left":y+=0;break;case "center":y+=1;break;case "line-right":y+=2;break;default:switch(M.textAlign){case 0:y+=0;break;case 2:y+=1;break;
case 1:y+=2}}L=y<0||y>8?7:y;M.xm=L}B=B.substring(LM.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");d=M;M={};if(B.indexOf("<")<0&&B.indexOf("&")<0)c=PGO(t,q,5,d),t=new eu(t,q,5,c.id,B,!1,g.UL(M)?void 0:M),P.push(c),P.push(t),c.S.push(t);else for(L=B.split(f6f),L.length===1?(B=5,d=PGO(t,q,B,d)):(y=B=6,d=Object.assign({Xv:32},d),d=new QC(t,q,y,"_"+bs++,d)),P.push(d),y=t,k=0;k<L.length;k++)if(w=L[k],k%2===0){X=Ru(`<html>${w}</html>`);let R;X.getElementsByTagName("parsererror").length?(R=X.createElement("span"),
R.appendChild(X.createTextNode(w))):R=X.firstChild;BYv(this,y,q-(y-t),B,d,k>0,R,M,P)}else y=A9(w)+c}LM.lastIndex=0}}return P}},NY7=/^NOTE/,G7F=/(?:\r\n|\r|\n){2,}/,LM=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),f6f=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var W1k=class extends g.x{constructor(W,z){super();this.Z=W;this.D=z;this.S=null;this.h7=this.Z.WG();this.logger=new g.GT("caps")}clear(){this.S&&this.S.dispose();this.S=null}reset(){this.S&&this.S.reset()}xA(){super.xA();this.clear()}};var k7o={windowColor:"#080808",windowOpacity:0,textAlign:2,xm:7,xj:50,yS:100,isDefault:!0,oO:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},ytf={windowColor:"#080808",windowOpacity:0,textAlign:0,xm:7,xj:50,yS:100,isDefault:!0,oO:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.cR("captions",class extends g.x5{constructor(W){super(W);this.Z=W;this.Gj=[];this.S4={};this.HF={};this.J=!1;this.N="NONE";this.S=this.O=this.X=this.R0=this.u9=null;this.TB={P6:()=>{this.P6()},
rR:(B,c,M,t,q=0)=>{const w=Number(this.videoData.C().f6().S.Jp(g.dgY)??0);q>0&&w>0&&this.videoData.lengthSeconds>0&&q/this.videoData.lengthSeconds>w?this.Z.j("tts",{dropcap:q}):this.rR(B,c,M,t)}};
this.dj=this.B=null;this.D=this.Z.C();this.videoData=this.Z.getVideoData();this.UB=this.Z.Rp();this.G={oO:{}};this.K={oO:{}};g.Ia(this.videoData)?this.N="OFFLINE":g.CLv(this.videoData,this.Z)?this.N="HLS":Gcy(this.videoData,this.Z)?this.N="SABR_LIVE":g.TQe(this.videoData,this.Z)?this.N="LIVE":this.videoData.captionTracks.length?this.N="INNERTUBE":this.videoData.fK&&(this.N="TTS");this.m7=this.D.controlsType==="3";this.Vf=new W1k(this.Z,this.D);this.i9=new g.GL(this);this.A=new g.jc({V:"div",Tj:"ytp-caption-window-container",
zj:{id:"ytp-caption-window-container"}});this.U={top:0,right:0,bottom:0,left:0,width:1,height:1};let z=null;const P=g.ag("yt-html5-player-modules::subtitlesModuleData");P&&(z=new g.F1(P));this.storage=z;this.tp=!!W.NO()?.YA();this.L=odG(this);this.EB=!this.L&&this.m7&&this.tp&&(this.N==="LIVE"||this.N==="SABR_LIVE");g.v(this,this.Vf);this.L?this.YA=this.e4=null:(this.e4=new g.MJ(this.m$,void 0,this),g.v(this,this.e4),this.YA=new g.wW(this.Mj,2E3,this),g.v(this,this.YA));g.v(this,this.i9);g.Xx(this.player,
this.A.element,4);g.v(this,this.A);this.L||this.i9.gj(W,"resize",this.j4);(this.yI=g.H_(this.D)&&!g.a7()&&!this.Z.isFullscreen()&&!this.L&&!this.EB)&&this.i9.gj(W,"resize",this.d7);this.i9.gj(W,"onPlaybackAudioChange",this.Y6);this.i9.gj(W,g.hN("captions"),B=>{this.onCueRangeEnter(B)});
this.i9.gj(W,g.es("captions"),B=>{this.onCueRangeExit(B)});
us(this,F7()||{});g.Tv(this.player,"onCaptionsModuleAvailable");this.N==="HLS"&&this.L&&(W=this.Z.NO().Ws(),this.tp&&this.i9.gj(W.textTracks,"addtrack",this.WZ))}xA(){if(this.L||this.EB){const W=this.Z.NO();W&&!W.hp()&&W.O()}else GG(this,!1);super.xA()}ot(){if(this.m7)return this.L||this.EB;if(this.N==="HLS")return this.L;var W=this.getAudioTrack();if(XK7(this)){if(!W.captionTracks.length)return!1;if(!this.S)return!0}W=ZH(W,g.C_(this.D));return W==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:W==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
fR(this):Ns(this)||fR(this)?!0:dOH(this)}load(){super.load();this.O=this.getAudioTrack();if(this.S)this.B&&(this.Vf.clear(),this.L?iOD(this,!0):this.player.getPresentingPlayerType()!==3&&this.S.A(this.B,"json3",this.TB),this.N!=="HLS"&&this.L||this.EB||WP(this)||g.Tv(this.player,"captionschanged",nR(this.B)));else{if(this.N==="OFFLINE")var W=new Edk(this.player,this.videoData,this.getAudioTrack());else this.N==="SABR_LIVE"?W=new uWo(this.videoData.S,this.player):this.N==="HLS"?W=new FCv(this.player):
this.N==="LIVE"?W=new vdU(this.videoData.S,this.player):this.N==="INNERTUBE"?W=new $OG(this.player,this.videoData,this.getAudioTrack()):(W=this.videoData,W=new s2Y(this.player,this.videoData.fK,this.videoData.videoId,W.captionsLanguagePreference||W.BF.captionsLanguagePreference||g.lr(W,"yt:cc_default_lang")||W.BF.tp,this.videoData.Q$,this.videoData.eventId));this.S=W;g.v(this,this.S);this.S.L(this.TB)}}unload(){this.L&&this.B?iOD(this,!1):(this.YA&&this.YA.Ju(),this.player.o6("captions"),this.Gj=
[],this.S&&this.S.N(),this.Vf.clear(),this.X&&this.player.Ql(this.X),this.j4());super.unload();this.player.s_();g.Tv(this.player,"captionschanged",{})}create(){this.ot()&&this.load();var W;a:{if(this.D.Y("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(W=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const z of W)if(z.kind==="asr"&&z.languageCode==="en"){W=
!0;break a}W=!1}W&&this.Z.rj("showpromotooltip",this.A.element)}P6(){var W=ZH(this.player.getAudioTrack(),g.C_(this.D));var z=W==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?PP(this,this.J):W==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&fR(this)?zI(this):Ns(this)||this.J||dOH(this)?PP(this,this.J):fR(this)?zI(this):null;if(this.N!=="HLS"&&this.L||this.EB){const P=this.S.S.S(!0);W=[];for(let B=0;B<P.length;B++){const c=P[B],M=g.dK("TRACK");M.setAttribute("kind","subtitles");M.setAttribute("label",g.Y2(c));M.setAttribute("srclang",
g.nn(c));M.setAttribute("id",c.toString());this.EB||M.setAttribute("src",this.S.K(c,"vtt"));c===z&&M.setAttribute("default","1");W.push(M)}z=this.Z.NO();z.S4(W);W=z.Ws();this.tp&&this.i9.gj(W.textTracks,"change",this.yT)}else!this.B&&z&&qD(this,z),g.Tv(this.player,"onCaptionsTrackListChanged"),g.AG(this.player,"onApiChange")}getTrackById(W){const z=this.S.S.S(!0);for(let P=0;P<z.length;P++)if(z[P].toString()===W)return z[P];return null}yT(){const W=this.Z.NO().Ws().textTracks;let z=null;for(let P=
0;P<W.length;P++)W[P].mode==="showing"&&(z=this.getTrackById(W[P].id));(this.loaded?this.B:null)!==z&&qD(this,z,!0)}WZ(){this.S?.L(this.TB)}Xi(){!this.B&&this.L||this.unload()}rR(W,z,P,B){if(W){t0(this,this.B??void 0);this.S.EB()&&(this.Gj=[],this.Z.o6("captions"),YW(this.e4),this.Vf.reset());a:{var c=this.Vf;B=B||0;P=M2n(c,W,P||0);W=[];try{for(const e of P){const b=e.trackData,a=e.cX,U=c.D.Y("safari_live_drm_captions_fix");if(typeof b!=="string"){P=W;var M=P.concat;if(U&&zzk(b))var t=qHD(c,b,a);
else{var q=c,w=z,y=b,L=a,k=B;if(!H1y(y))throw Error("Invalid binary caption track data");q.S||(q.S=new CGU(k,w));t=q.S.N(y,L)}var d=M.call(P,t)}else{if(b.substring(0,6)==="WEBVTT")var X=W.concat(qHD(c,b,a));else{P=W;var D=P.concat;b:{w=c;q=z;if(b[0]==="{")try{w.S||(w.S=new JtH(wKH(q)));var R=w.S.N(b,a);break b}catch(oy){g.T(oy);R=[];break b}const zU=Ru(b);if(!zU||!zU.firstChild){const oy=Error("Invalid caption track data");oy.params=b;throw oy;}if(zU.firstChild.tagName==="timedtext"){if(Number(zU.firstChild.getAttribute("format"))===
3){y=zU;w.S||(w.S=new HOo(wKH(q)));R=w.S.N(y,a);break b}const oy=Error("Unsupported subtitles format in web player (Format2)");oy.params=b;throw oy;}if(zU.firstChild.tagName==="transcript"){const oy=Error("Unsupported subtitles format in web player (Format1)");oy.params=b;throw oy;}const go=Error("Invalid caption track data");go.params=b;throw go;}X=D.call(P,R)}d=X}W=d}var I=W;break a}catch(e){g.Nc(c.logger,187101178,`Captions parsing failed: ${e.message}. `);c.clear();I=[];break a}I=void 0}this.D.Y("html5_sabr_live_support_subfragmented_captions")&&
this.S instanceof uWo&&(z=this.S.X,c=[],I.length>0&&(c=I.slice(z.N.length)),z.N=!z.S||z.S.info.yO?[]:I,I=c);I.length>0&&(z=this.B,this.E9(z,!!z,WP(this)?"g":this.J?"m":"s"));this.player.Ql(I,void 0,this.N==="LIVE"||this.N==="SABR_LIVE");!this.J||this.EB||WP(this)||g.zN(this.D)||g.AO(this.D)||g.U$(this.D)||this.D.O==="shortspage"||this.player.isInline()||(this.YA.Ju(),I=IqH({xm:0,xj:5,yS:5,ow:2,textAlign:0,E7:0,lang:"en"}),this.R0=[I],z=["Click "," for settings"],this.u9||(c=new g.NwH({V:"svg",zj:{height:"100%",
version:"1.1",viewBox:"0 0 36 36",width:"100%"},o0:[{V:"path",Jw:!0,zj:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.v(this,c),this.u9=c.element),c=I.end-I.start,(d=g.Y2(this.B))&&this.R0.push(new eu(I.start,c,0,I.id,d)),this.R0.push(new eu(I.start,c,0,I.id,z[0]),new eu(I.start,c,0,I.id,this.u9,!0),new eu(I.start,c,0,I.id,z[1],!0)),this.player.Ql(this.R0),this.YA.I4());!this.J||this.EB||WP(this)||(this.D.Y("enable_player_captions_persistence_state_machine")?BP(this,!0):g.C_(this.D)?cP(this,!0):MD(this,!0),this.O&&(this.O.L=this.B),this.player.s_());this.J=!1}}onCueRangeEnter(W){this.Gj.push(W);
YW(this.e4)}onCueRangeExit(W){g.Av(this.Gj,W);this.S instanceof vdU&&this.S.U&&this.player.J$([W]);YW(this.e4)}getCaptionWindowContainerId(){return this.A.element.id}Mj(){LCY(this,this.R0);this.R0=null}m$(){if(!this.yI||!this.L){this.e4.stop();g.Jc(this.HF);this.Gj.sort(g.pA);var W=this.Gj;if(this.X){const z=g.ew(W,function(P){return this.X.indexOf(P)===-1},this);
z.length&&(W=z)}for(const z of W)z instanceof QC?KCD(this,z):mO2(this,z);for(const [z,P]of Object.entries(this.S4)){const B=z,c=P;this.HF[B]?(c.element.parentNode||(c instanceof YHv||c instanceof OO2||g.sL(this.S4,(M,t)=>{t!==B&&M.N.params.xm===c.N.params.xm&&M.N.params.xj===c.N.params.xj&&M.N.params.yS===c.N.params.yS&&(M.dispose(),delete this.S4[t]);return t===B},this),this.A.element.appendChild(c.element)),c.X(this.HF[B])):(c.dispose(),delete this.S4[B])}}}cY(){us(this,{},!0);
g.Tv(this.player,"captionssettingschanged")}e$(){var W=this.D.Y("enable_player_captions_new_style_defaults")?ytf:k7o,z=W.oO;W={background:z.background,backgroundOpacity:z.backgroundOpacity,charEdgeStyle:z.charEdgeStyle,color:z.color,fontFamily:z.fontFamily,fontSizeIncrement:z.fontSizeIncrement,fontStyle:z.bold&&z.italic?3:z.bold?1:z.italic?2:0,textOpacity:z.textOpacity,windowColor:W.windowColor,windowOpacity:W.windowOpacity};z=F7()||{};z.background!=null&&(W.background=z.background);z.backgroundOverride!=
null&&(W.backgroundOverride=z.backgroundOverride);z.backgroundOpacity!=null&&(W.backgroundOpacity=z.backgroundOpacity);z.backgroundOpacityOverride!=null&&(W.backgroundOpacityOverride=z.backgroundOpacityOverride);z.charEdgeStyle!=null&&(W.charEdgeStyle=z.charEdgeStyle);z.charEdgeStyleOverride!=null&&(W.charEdgeStyleOverride=z.charEdgeStyleOverride);z.color!=null&&(W.color=z.color);z.colorOverride!=null&&(W.colorOverride=z.colorOverride);z.fontFamily!=null&&(W.fontFamily=z.fontFamily);z.fontFamilyOverride!=
null&&(W.fontFamilyOverride=z.fontFamilyOverride);z.fontSizeIncrement!=null&&(W.fontSizeIncrement=z.fontSizeIncrement);z.fontSizeIncrementOverride!=null&&(W.fontSizeIncrementOverride=z.fontSizeIncrementOverride);z.fontStyle!=null&&(W.fontStyle=z.fontStyle);z.fontStyleOverride!=null&&(W.fontStyleOverride=z.fontStyleOverride);z.textOpacity!=null&&(W.textOpacity=z.textOpacity);z.textOpacityOverride!=null&&(W.textOpacityOverride=z.textOpacityOverride);z.windowColor!=null&&(W.windowColor=z.windowColor);
z.windowColorOverride!=null&&(W.windowColorOverride=z.windowColorOverride);z.windowOpacity!=null&&(W.windowOpacity=z.windowOpacity);z.windowOpacityOverride!=null&&(W.windowOpacityOverride=z.windowOpacityOverride);return W}Xm(W,z){const P={};Object.assign(P,F7());Object.assign(P,W);us(this,P,z);g.Tv(this.player,"captionssettingschanged")}j4(){!this.L&&this.loaded&&(g.RB(this.S4,function(W,z){W.dispose();delete this.S4[z]},this),this.m$())}Z5(W,z){switch(W){case "fontSize":if(isNaN(z))break;
W=g.mh(z,-2,4);this.Xm({fontSizeIncrement:W});return W;case "reload":z&&!this.L&&qD(this,this.B,!0);break;case "stickyLoading":z!==void 0&&this.D.A&&(this.D.Y("enable_player_captions_persistence_state_machine")?BP(this,!(!z||!z.userInitiated)):g.C_(this.D)?cP(this,!!z):MD(this,!!z));break;case "track":return nde(this,z);case "tracklist":return this.S?g.bw(this.S.S.S(!(!z||!z.includeAsr)),P=>nR(P)):[];
case "translationLanguages":return this.S?this.S.O.map(P=>Object.assign({},P)):[];
case "sampleSubtitles":this.L||z===void 0||GG(this,!!z);break;case "sampleSubtitlesCustomized":this.L||GG(this,!!z,z);break;case "recommendedTranslationLanguages":return g.TY();case "defaultTranslationSourceTrackIndices":return this.S?this.S.S4:[]}}getOptions(){const W="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.D.A&&W.push("stickyLoading");return W}vp(){let W=this.B;if(this.Z.pW("captions")){if(this.D.Y("html5_modify_caption_vss_logging"))return(W=this.videoData.D5??
null)?{cc:g.ZI(W)}:{};if(W){let z=W.vssId;W.translationLanguage&&z&&(z=`t${z}.${g.nn(W)}`);return{cc:z}}}return{}}Rc(W){this.isSubtitlesOn()?(this.D.Y("enable_player_captions_persistence_state_machine")&&W?BP(this,!1):g.C_(this.D)?cP(this,!1):MD(this,!1),t0(this),qD(this,null,!0)):this.QN(W)}QN(W){const z=WP(this)||!this.B?PP(this,!0):this.B;z&&this.V9(z.vssId,"m");this.isSubtitlesOn()||qD(this,z,this.D.Y("enable_player_captions_persistence_state_machine")?W:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.B&&!WP(this)}Y6(){const W=WP(this);fR(this,W)?qD(this,this.getAudioTrack().S,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),XK7(this)&&(this.J=!1,this.B=null,this.S&&(this.S.dispose(),this.S=null)),this.ot()&&(W?qD(this,PP(this,!1),!1):this.load()))}MX(W){if(this.D.experiments.cF("web_enable_captions_set_target_container")&&W!==this.dj){var z=this.A.element;z.parentNode&&g.lT(z);(this.dj=W)?(this.dj.appendChild(z),z.style.position="absolute",z.style.bottom="0",z.style.left=
"0",z.style.width="100%",z.style.height="auto",z.style.top="auto"):(g.Xx(this.player,z,4),z.style.position="absolute",z.style.bottom="auto",z.style.left="0",z.style.width="100%",z.style.height="100%",z.style.top="0");this.j4()}}Ua(W){W&&(this.U={top:W.top,right:W.right,bottom:W.bottom,left:W.left,width:1-W.left-W.right,height:1-W.top-W.bottom},this.A.element.style.top=`${this.U.top*100}%`,this.A.element.style.left=`${this.U.left*100}%`,this.A.element.style.width=`${this.U.width*100}%`,this.A.element.style.height=
`${this.U.height*100}%`,this.A.element.style.position="absolute",W=DOv(this))&&(this.A.element.style.width=`${W.width}px`,this.A.element.style.height=`${W.height}px`)}onVideoDataChange(W,z){W==="newdata"&&(this.videoData=z,this.loaded&&this.unload(),this.J=!1,this.B=null,this.S&&(this.S.dispose(),this.S=null,g.Tv(this.player,"captionschanged",{})),this.ot()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}d7(){const W=this.Z.NO();W&&!W.hp()&&W.O();this.Z.isFullscreen()?(this.L=this.m7=
!0,this.loaded&&this.P6()):(this.m7=this.D.controlsType==="3",this.L=odG(this));qD(this,this.B)}qs(){const W=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;W&&g.Cz(this.player,"innertubeCommand",W)}E9(W,z,P){const B=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let c="";W&&(c=W.vssId,c=c.replace(B,""));let M="";W&&W.getId()&&(M=W.getId()||"");W&&W.getXtags()&&(W=W.getXtags(),W=W.replace(B,""),M=M.concat(`;${W}`));this.N==="HLS"&&(M="");this.Z.E9(z?c:"",z?M:
"",P)}V9(W,z){W=(W||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");W.length>0&&this.Z.V9(W,z)}});})(_yt_player);
